name: RDP via Ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Install Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok
    - name: Start RDP
      run: |
        sudo apt update
        sudo apt install xrdp xfce4 xfce4-goodies -y
        sudo service xrdp start
    - name: Configure Ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
        ngrok config add-authtoken $NGROK_TOKEN
        nohup ngrok tcp 3389 --region ap &

    - name: Get Ngrok URL
      run: |
        sleep 5
        curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ngrok_url.txt
        cat ngrok_url.txt

    - name: Output Ngrok URL
      run: |
        echo "RDP is available at:"
        cat ngrok_url.txt
